[options]
girs_dir = "../gir-files"
work_mode = "sys"
library = "OSTree"
version = "1.0"
min_cfg_version = "1.0"
target_path = "."

external_libraries = [
   "GLib",
   "Gio",
   "GObject",
]

ignore = [

]
